//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace QISMsgVaultWeb.MsgVaultSvc {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MongoMail", Namespace="http://schemas.datacontract.org/2004/07/QISMsgVaultWeb.Web")]
    public partial class MongoMail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BodyField;
        
        private string CCField;
        
        private string CategoriesField;
        
        private System.DateTime CreationTimeField;
        
        private string EntryIDField;
        
        private QISMsgVaultWeb.MsgVaultSvc.ObjectId IdField;
        
        private System.DateTime ReceivedTimeField;
        
        private string SenderEmailAddressField;
        
        private string SubjectField;
        
        private string ToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CC {
            get {
                return this.CCField;
            }
            set {
                if ((object.ReferenceEquals(this.CCField, value) != true)) {
                    this.CCField = value;
                    this.RaisePropertyChanged("CC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntryID {
            get {
                return this.EntryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryIDField, value) != true)) {
                    this.EntryIDField = value;
                    this.RaisePropertyChanged("EntryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QISMsgVaultWeb.MsgVaultSvc.ObjectId Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReceivedTime {
            get {
                return this.ReceivedTimeField;
            }
            set {
                if ((this.ReceivedTimeField.Equals(value) != true)) {
                    this.ReceivedTimeField = value;
                    this.RaisePropertyChanged("ReceivedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderEmailAddress {
            get {
                return this.SenderEmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderEmailAddressField, value) != true)) {
                    this.SenderEmailAddressField = value;
                    this.RaisePropertyChanged("SenderEmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectId", Namespace="http://schemas.datacontract.org/2004/07/MongoDB.Bson")]
    public partial struct ObjectId : System.ComponentModel.INotifyPropertyChanged {
        
        private int _incrementField;
        
        private int _machineField;
        
        private short _pidField;
        
        private int _timestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _increment {
            get {
                return this._incrementField;
            }
            set {
                if ((this._incrementField.Equals(value) != true)) {
                    this._incrementField = value;
                    this.RaisePropertyChanged("_increment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _machine {
            get {
                return this._machineField;
            }
            set {
                if ((this._machineField.Equals(value) != true)) {
                    this._machineField = value;
                    this.RaisePropertyChanged("_machine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short _pid {
            get {
                return this._pidField;
            }
            set {
                if ((this._pidField.Equals(value) != true)) {
                    this._pidField = value;
                    this.RaisePropertyChanged("_pid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _timestamp {
            get {
                return this._timestampField;
            }
            set {
                if ((this._timestampField.Equals(value) != true)) {
                    this._timestampField = value;
                    this.RaisePropertyChanged("_timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VaultUser", Namespace="http://schemas.datacontract.org/2004/07/QISMsgVaultWeb.Web")]
    public partial class VaultUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime CreationTimeField;
        
        private QISMsgVaultWeb.MsgVaultSvc.ObjectId IdField;
        
        private System.DateTime LastUpdatedField;
        
        private string emailAddressField;
        
        private bool initializedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QISMsgVaultWeb.MsgVaultSvc.ObjectId Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdated {
            get {
                return this.LastUpdatedField;
            }
            set {
                if ((this.LastUpdatedField.Equals(value) != true)) {
                    this.LastUpdatedField = value;
                    this.RaisePropertyChanged("LastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.emailAddressField, value) != true)) {
                    this.emailAddressField = value;
                    this.RaisePropertyChanged("emailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool initialized {
            get {
                return this.initializedField;
            }
            set {
                if ((this.initializedField.Equals(value) != true)) {
                    this.initializedField = value;
                    this.RaisePropertyChanged("initialized");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MsgVaultSvc.IMsgVaultService")]
    public interface IMsgVaultService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMsgVaultService/GetAllEmails", ReplyAction="http://tempuri.org/IMsgVaultService/GetAllEmailsResponse")]
        System.IAsyncResult BeginGetAllEmails(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail> EndGetAllEmails(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMsgVaultService/GetEmailsPage", ReplyAction="http://tempuri.org/IMsgVaultService/GetEmailsPageResponse")]
        System.IAsyncResult BeginGetEmailsPage(int pageIndex, int pageSize, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail> EndGetEmailsPage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMsgVaultService/UploadEmail", ReplyAction="http://tempuri.org/IMsgVaultService/UploadEmailResponse")]
        System.IAsyncResult BeginUploadEmail(QISMsgVaultWeb.MsgVaultSvc.MongoMail msg, System.AsyncCallback callback, object asyncState);
        
        void EndUploadEmail(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMsgVaultService/CreateUser", ReplyAction="http://tempuri.org/IMsgVaultService/CreateUserResponse")]
        System.IAsyncResult BeginCreateUser(QISMsgVaultWeb.MsgVaultSvc.VaultUser user, System.AsyncCallback callback, object asyncState);
        
        void EndCreateUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMsgVaultService/GetUserByEmail", ReplyAction="http://tempuri.org/IMsgVaultService/GetUserByEmailResponse")]
        System.IAsyncResult BeginGetUserByEmail(string emailaddr, System.AsyncCallback callback, object asyncState);
        
        QISMsgVaultWeb.MsgVaultSvc.VaultUser EndGetUserByEmail(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMsgVaultService/UpdateUser", ReplyAction="http://tempuri.org/IMsgVaultService/UpdateUserResponse")]
        System.IAsyncResult BeginUpdateUser(QISMsgVaultWeb.MsgVaultSvc.VaultUser user, System.AsyncCallback callback, object asyncState);
        
        void EndUpdateUser(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMsgVaultServiceChannel : QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllEmailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllEmailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEmailsPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEmailsPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserByEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserByEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QISMsgVaultWeb.MsgVaultSvc.VaultUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QISMsgVaultWeb.MsgVaultSvc.VaultUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MsgVaultServiceClient : System.ServiceModel.ClientBase<QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService>, QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService {
        
        private BeginOperationDelegate onBeginGetAllEmailsDelegate;
        
        private EndOperationDelegate onEndGetAllEmailsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllEmailsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetEmailsPageDelegate;
        
        private EndOperationDelegate onEndGetEmailsPageDelegate;
        
        private System.Threading.SendOrPostCallback onGetEmailsPageCompletedDelegate;
        
        private BeginOperationDelegate onBeginUploadEmailDelegate;
        
        private EndOperationDelegate onEndUploadEmailDelegate;
        
        private System.Threading.SendOrPostCallback onUploadEmailCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateUserDelegate;
        
        private EndOperationDelegate onEndCreateUserDelegate;
        
        private System.Threading.SendOrPostCallback onCreateUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserByEmailDelegate;
        
        private EndOperationDelegate onEndGetUserByEmailDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserByEmailCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateUserDelegate;
        
        private EndOperationDelegate onEndUpdateUserDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MsgVaultServiceClient() {
        }
        
        public MsgVaultServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MsgVaultServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsgVaultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsgVaultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAllEmailsCompletedEventArgs> GetAllEmailsCompleted;
        
        public event System.EventHandler<GetEmailsPageCompletedEventArgs> GetEmailsPageCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UploadEmailCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CreateUserCompleted;
        
        public event System.EventHandler<GetUserByEmailCompletedEventArgs> GetUserByEmailCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdateUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService.BeginGetAllEmails(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllEmails(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail> QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService.EndGetAllEmails(System.IAsyncResult result) {
            return base.Channel.EndGetAllEmails(result);
        }
        
        private System.IAsyncResult OnBeginGetAllEmails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService)(this)).BeginGetAllEmails(callback, asyncState);
        }
        
        private object[] OnEndGetAllEmails(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail> retVal = ((QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService)(this)).EndGetAllEmails(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllEmailsCompleted(object state) {
            if ((this.GetAllEmailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllEmailsCompleted(this, new GetAllEmailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllEmailsAsync() {
            this.GetAllEmailsAsync(null);
        }
        
        public void GetAllEmailsAsync(object userState) {
            if ((this.onBeginGetAllEmailsDelegate == null)) {
                this.onBeginGetAllEmailsDelegate = new BeginOperationDelegate(this.OnBeginGetAllEmails);
            }
            if ((this.onEndGetAllEmailsDelegate == null)) {
                this.onEndGetAllEmailsDelegate = new EndOperationDelegate(this.OnEndGetAllEmails);
            }
            if ((this.onGetAllEmailsCompletedDelegate == null)) {
                this.onGetAllEmailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllEmailsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllEmailsDelegate, null, this.onEndGetAllEmailsDelegate, this.onGetAllEmailsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService.BeginGetEmailsPage(int pageIndex, int pageSize, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEmailsPage(pageIndex, pageSize, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail> QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService.EndGetEmailsPage(System.IAsyncResult result) {
            return base.Channel.EndGetEmailsPage(result);
        }
        
        private System.IAsyncResult OnBeginGetEmailsPage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int pageIndex = ((int)(inValues[0]));
            int pageSize = ((int)(inValues[1]));
            return ((QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService)(this)).BeginGetEmailsPage(pageIndex, pageSize, callback, asyncState);
        }
        
        private object[] OnEndGetEmailsPage(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail> retVal = ((QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService)(this)).EndGetEmailsPage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEmailsPageCompleted(object state) {
            if ((this.GetEmailsPageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEmailsPageCompleted(this, new GetEmailsPageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEmailsPageAsync(int pageIndex, int pageSize) {
            this.GetEmailsPageAsync(pageIndex, pageSize, null);
        }
        
        public void GetEmailsPageAsync(int pageIndex, int pageSize, object userState) {
            if ((this.onBeginGetEmailsPageDelegate == null)) {
                this.onBeginGetEmailsPageDelegate = new BeginOperationDelegate(this.OnBeginGetEmailsPage);
            }
            if ((this.onEndGetEmailsPageDelegate == null)) {
                this.onEndGetEmailsPageDelegate = new EndOperationDelegate(this.OnEndGetEmailsPage);
            }
            if ((this.onGetEmailsPageCompletedDelegate == null)) {
                this.onGetEmailsPageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEmailsPageCompleted);
            }
            base.InvokeAsync(this.onBeginGetEmailsPageDelegate, new object[] {
                        pageIndex,
                        pageSize}, this.onEndGetEmailsPageDelegate, this.onGetEmailsPageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService.BeginUploadEmail(QISMsgVaultWeb.MsgVaultSvc.MongoMail msg, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUploadEmail(msg, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService.EndUploadEmail(System.IAsyncResult result) {
            base.Channel.EndUploadEmail(result);
        }
        
        private System.IAsyncResult OnBeginUploadEmail(object[] inValues, System.AsyncCallback callback, object asyncState) {
            QISMsgVaultWeb.MsgVaultSvc.MongoMail msg = ((QISMsgVaultWeb.MsgVaultSvc.MongoMail)(inValues[0]));
            return ((QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService)(this)).BeginUploadEmail(msg, callback, asyncState);
        }
        
        private object[] OnEndUploadEmail(System.IAsyncResult result) {
            ((QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService)(this)).EndUploadEmail(result);
            return null;
        }
        
        private void OnUploadEmailCompleted(object state) {
            if ((this.UploadEmailCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UploadEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UploadEmailAsync(QISMsgVaultWeb.MsgVaultSvc.MongoMail msg) {
            this.UploadEmailAsync(msg, null);
        }
        
        public void UploadEmailAsync(QISMsgVaultWeb.MsgVaultSvc.MongoMail msg, object userState) {
            if ((this.onBeginUploadEmailDelegate == null)) {
                this.onBeginUploadEmailDelegate = new BeginOperationDelegate(this.OnBeginUploadEmail);
            }
            if ((this.onEndUploadEmailDelegate == null)) {
                this.onEndUploadEmailDelegate = new EndOperationDelegate(this.OnEndUploadEmail);
            }
            if ((this.onUploadEmailCompletedDelegate == null)) {
                this.onUploadEmailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUploadEmailCompleted);
            }
            base.InvokeAsync(this.onBeginUploadEmailDelegate, new object[] {
                        msg}, this.onEndUploadEmailDelegate, this.onUploadEmailCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService.BeginCreateUser(QISMsgVaultWeb.MsgVaultSvc.VaultUser user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateUser(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService.EndCreateUser(System.IAsyncResult result) {
            base.Channel.EndCreateUser(result);
        }
        
        private System.IAsyncResult OnBeginCreateUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            QISMsgVaultWeb.MsgVaultSvc.VaultUser user = ((QISMsgVaultWeb.MsgVaultSvc.VaultUser)(inValues[0]));
            return ((QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService)(this)).BeginCreateUser(user, callback, asyncState);
        }
        
        private object[] OnEndCreateUser(System.IAsyncResult result) {
            ((QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService)(this)).EndCreateUser(result);
            return null;
        }
        
        private void OnCreateUserCompleted(object state) {
            if ((this.CreateUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateUserAsync(QISMsgVaultWeb.MsgVaultSvc.VaultUser user) {
            this.CreateUserAsync(user, null);
        }
        
        public void CreateUserAsync(QISMsgVaultWeb.MsgVaultSvc.VaultUser user, object userState) {
            if ((this.onBeginCreateUserDelegate == null)) {
                this.onBeginCreateUserDelegate = new BeginOperationDelegate(this.OnBeginCreateUser);
            }
            if ((this.onEndCreateUserDelegate == null)) {
                this.onEndCreateUserDelegate = new EndOperationDelegate(this.OnEndCreateUser);
            }
            if ((this.onCreateUserCompletedDelegate == null)) {
                this.onCreateUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateUserCompleted);
            }
            base.InvokeAsync(this.onBeginCreateUserDelegate, new object[] {
                        user}, this.onEndCreateUserDelegate, this.onCreateUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService.BeginGetUserByEmail(string emailaddr, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserByEmail(emailaddr, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QISMsgVaultWeb.MsgVaultSvc.VaultUser QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService.EndGetUserByEmail(System.IAsyncResult result) {
            return base.Channel.EndGetUserByEmail(result);
        }
        
        private System.IAsyncResult OnBeginGetUserByEmail(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string emailaddr = ((string)(inValues[0]));
            return ((QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService)(this)).BeginGetUserByEmail(emailaddr, callback, asyncState);
        }
        
        private object[] OnEndGetUserByEmail(System.IAsyncResult result) {
            QISMsgVaultWeb.MsgVaultSvc.VaultUser retVal = ((QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService)(this)).EndGetUserByEmail(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserByEmailCompleted(object state) {
            if ((this.GetUserByEmailCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserByEmailCompleted(this, new GetUserByEmailCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserByEmailAsync(string emailaddr) {
            this.GetUserByEmailAsync(emailaddr, null);
        }
        
        public void GetUserByEmailAsync(string emailaddr, object userState) {
            if ((this.onBeginGetUserByEmailDelegate == null)) {
                this.onBeginGetUserByEmailDelegate = new BeginOperationDelegate(this.OnBeginGetUserByEmail);
            }
            if ((this.onEndGetUserByEmailDelegate == null)) {
                this.onEndGetUserByEmailDelegate = new EndOperationDelegate(this.OnEndGetUserByEmail);
            }
            if ((this.onGetUserByEmailCompletedDelegate == null)) {
                this.onGetUserByEmailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserByEmailCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserByEmailDelegate, new object[] {
                        emailaddr}, this.onEndGetUserByEmailDelegate, this.onGetUserByEmailCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService.BeginUpdateUser(QISMsgVaultWeb.MsgVaultSvc.VaultUser user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateUser(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService.EndUpdateUser(System.IAsyncResult result) {
            base.Channel.EndUpdateUser(result);
        }
        
        private System.IAsyncResult OnBeginUpdateUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            QISMsgVaultWeb.MsgVaultSvc.VaultUser user = ((QISMsgVaultWeb.MsgVaultSvc.VaultUser)(inValues[0]));
            return ((QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService)(this)).BeginUpdateUser(user, callback, asyncState);
        }
        
        private object[] OnEndUpdateUser(System.IAsyncResult result) {
            ((QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService)(this)).EndUpdateUser(result);
            return null;
        }
        
        private void OnUpdateUserCompleted(object state) {
            if ((this.UpdateUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateUserAsync(QISMsgVaultWeb.MsgVaultSvc.VaultUser user) {
            this.UpdateUserAsync(user, null);
        }
        
        public void UpdateUserAsync(QISMsgVaultWeb.MsgVaultSvc.VaultUser user, object userState) {
            if ((this.onBeginUpdateUserDelegate == null)) {
                this.onBeginUpdateUserDelegate = new BeginOperationDelegate(this.OnBeginUpdateUser);
            }
            if ((this.onEndUpdateUserDelegate == null)) {
                this.onEndUpdateUserDelegate = new EndOperationDelegate(this.OnEndUpdateUser);
            }
            if ((this.onUpdateUserCompletedDelegate == null)) {
                this.onUpdateUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateUserCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateUserDelegate, new object[] {
                        user}, this.onEndUpdateUserDelegate, this.onUpdateUserCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService CreateChannel() {
            return new MsgVaultServiceClientChannel(this);
        }
        
        private class MsgVaultServiceClientChannel : ChannelBase<QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService>, QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService {
            
            public MsgVaultServiceClientChannel(System.ServiceModel.ClientBase<QISMsgVaultWeb.MsgVaultSvc.IMsgVaultService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAllEmails(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllEmails", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail> EndGetAllEmails(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail> _result = ((System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail>)(base.EndInvoke("GetAllEmails", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetEmailsPage(int pageIndex, int pageSize, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = pageIndex;
                _args[1] = pageSize;
                System.IAsyncResult _result = base.BeginInvoke("GetEmailsPage", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail> EndGetEmailsPage(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail> _result = ((System.Collections.ObjectModel.ObservableCollection<QISMsgVaultWeb.MsgVaultSvc.MongoMail>)(base.EndInvoke("GetEmailsPage", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUploadEmail(QISMsgVaultWeb.MsgVaultSvc.MongoMail msg, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = msg;
                System.IAsyncResult _result = base.BeginInvoke("UploadEmail", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUploadEmail(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("UploadEmail", _args, result);
            }
            
            public System.IAsyncResult BeginCreateUser(QISMsgVaultWeb.MsgVaultSvc.VaultUser user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("CreateUser", _args, callback, asyncState);
                return _result;
            }
            
            public void EndCreateUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("CreateUser", _args, result);
            }
            
            public System.IAsyncResult BeginGetUserByEmail(string emailaddr, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = emailaddr;
                System.IAsyncResult _result = base.BeginInvoke("GetUserByEmail", _args, callback, asyncState);
                return _result;
            }
            
            public QISMsgVaultWeb.MsgVaultSvc.VaultUser EndGetUserByEmail(System.IAsyncResult result) {
                object[] _args = new object[0];
                QISMsgVaultWeb.MsgVaultSvc.VaultUser _result = ((QISMsgVaultWeb.MsgVaultSvc.VaultUser)(base.EndInvoke("GetUserByEmail", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateUser(QISMsgVaultWeb.MsgVaultSvc.VaultUser user, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = user;
                System.IAsyncResult _result = base.BeginInvoke("UpdateUser", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUpdateUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("UpdateUser", _args, result);
            }
        }
    }
}
